Wheel control/fixes
serykhelena/bb-8_project pull request #6
Opened 2020-09-11 08:44 UTC by Doraepod

2020-09-11 08:46 UTC, Doraepod commented on controller_bb_8_driver/tests/test_joystick.c
> +    robotOdometryInit();
gyroscopeInit вызывается в одометрии,можно не дублировать

2020-09-11 08:50 UTC, Doraepod commented on controller_bb_8_driver/src/robot_odometry.c
> +}
Тут нужно ограничить интервалом [0 360]. Меня вроде научили, что можно брать остаток от деления

2020-09-11 08:57 UTC, Doraepod commented on controller_bb_8_driver/src/robot_odometry.c
> +
Ошибку стоит проверять на оптимальную траекторию. Например, если задание 10 градусов, а текущий угол 359 градусов, то ошибка будет +11 градусов.

2020-09-11 09:22 UTC, Doraepod commented on controller_bb_8_driver/src/robot_odometry.c
> +
Тут как будто больше слагаемых чем нужно. Там откуда я списывал уравнения получаются:
v_x = angle_cos * v_x_glob - angle_sin * v_y_glob
v_y = angle_sin * v_x_glob + angle_cos * v_y_glob

2020-09-11 14:06 UTC, Doraepod commented on controller_bb_8_driver/src/robot_odometry.c
> +}
Clip нельзя, надо чтобы 361 превращалось в 1, а -1 в 359. Вроде бы angle_integral = angle_integral % 360 должно работать и для положительных и для отрицательных значений

2020-09-11 14:19 UTC, Doraepod commented on controller_bb_8_driver/src/robot_odometry.c
> +
Я вроде придумал вариант когда это не сработает, поэтому можно попробовать вот так:

float anglePropError = angle_integral - realAngle_Z;

if (anglePropError > 180)
    anglePropError -= 360;
else if (anglePropError  < -180)
    anglePropError += 360;

2020-09-11 14:56 UTC, serykhelena commented on controller_bb_8_driver/src/robot_odometry.c
> +
Так при каком варианте не сработает?

2020-09-11 15:00 UTC, Doraepod commented on controller_bb_8_driver/src/robot_odometry.c
> +
Например, задание на угол = 91, а текущий угол = 272. Получим -181 и пройдем мимо всех условий, а хотим +179

2020-09-11 15:02 UTC, serykhelena commented on controller_bb_8_driver/src/robot_odometry.c
> +
Мне показалось, что -181 и + 179 - это примерно одно и тоже.. только в разные стороны робот вращаться будет (=

2020-09-22 13:17 UTC, serykhelena submitted a review, later dismissed

2020-10-31 19:36 UTC, serykhelena requested changes

2020-10-31 19:36 UTC, serykhelena commented on controller_bb_8_driver/include/logger.h
> +             float value1,
А ты не хочешь передавать в эту функцию указатель на массив и его размер?

2020-10-31 19:36 UTC, serykhelena commented on controller_bb_8_driver/halconf.h
> +#define HAL_USE_UART                TRUE
А зачем? Вроде HAL_USE_SERIAL уже TRUE .. и ты вроде SD3 используешь, а это Serial. В чём разница не скажу, но буду благодарна если ты расскажешь (=

2020-10-31 19:36 UTC, serykhelena commented on controller_bb_8_driver/src/logger.c
> +             float value1,
здесь тоже самое из хэдера (про указатель на массив и размер)

2020-10-31 19:36 UTC, serykhelena commented on controller_bb_8_driver/src/logger.c
> +    logData.data[0] = value1;
и если у тебя будет массив в аргументах, эту штуку можно будет сделать через цикл (=

2020-10-31 19:36 UTC, serykhelena commented on controller_bb_8_driver/tests/test_logger.c
> +    log_data.mode = 0;
может эту штуку вынести в loggerInit() ? Сделать функцию. Правда там всего одна строчка... в общем, не знаю.. так на подумать (=

2020-10-31 19:36 UTC, serykhelena commented on python/joystick/joystick.py
> +        await asyncio.sleep(3)
это задержка на 3 секунды? Меня как-то это смущает ...

2020-10-31 19:36 UTC, serykhelena commented on python/joystick/src/robot_logging.py
> +        print(string_to_csv)
это просто для отладки? В любом случае я бы рекомендовала модуль logging использовать (как в joydtick.py мы делаем)

2020-10-31 19:36 UTC, serykhelena commented on python/joystick/src/robot_logging.py
> +        print(self.current_file)
аналогично для всех принтов. Или удалить совсем если они не нужны

2020-10-31 21:13 UTC, Doraepod commented on controller_bb_8_driver/include/logger.h
> +             float value1,
Неа, если честно. Массив все равно придется собирать, и снаружи это будет громоздко. А тут пусть и миллион строчек, но так как больше ничего нет, то все читаемо и выглядит вроде не слишком плохо.

2020-10-31 21:13 UTC, Doraepod commented on controller_bb_8_driver/halconf.h
> +#define HAL_USE_UART                TRUE
Это мусор, я пользовался юартом.

2020-10-31 21:17 UTC, Doraepod commented on controller_bb_8_driver/tests/test_logger.c
> +    log_data.mode = 0;
Я не уверен что это действительно инициализация. Просто первая посылка с мк идет с другим кодом, чтобы питон это увидел.

2020-10-31 21:19 UTC, Doraepod commented on python/joystick/joystick.py
> +        await asyncio.sleep(3)
Это только при старте программы в питоне. 360 геймпад в начале долго лагает. Если XONE этим не страдает можно будет убрать. Но вообще не думаю что это будет так заметно.

2020-10-31 21:19 UTC, Doraepod commented on python/joystick/src/robot_logging.py
> +        print(self.current_file)
Да, это мусор остался.

2020-10-31 21:30 UTC, Doraepod commented on controller_bb_8_driver/src/logger.c
> +    logData.data[0] = value1;
Да можно и не через цикл, наверное, а просто скопировать память, но все равно кажется собирать массив снаружи так себе.

2020-10-31 21:31 UTC, Doraepod commented on python/joystick/src/robot_logging.py
> +        print(string_to_csv)
Удалено.

2020-10-31 21:32 UTC, serykhelena commented on controller_bb_8_driver/include/logger.h
> +             float value1,
Я не очень понимаю почему... Почему нельзя написать что-то такое? 
void sendLog(SerialDriver *sdp, float *vals, uint8_t vals_size)
{
    uint8_t i = 0; 
    for(i = 0, i < vals_size, i++)
   {
        // можно ещё проверку на размер вставить
        logData.data[i] = vals[i];
   }
}

2020-10-31 21:41 UTC, Doraepod commented on controller_bb_8_driver/include/logger.h
> +             float value1,
Обработать входной массив не проблема. Но это получается что собирать массив надо снаружи в мейне. Если хочешь, сделаю так. Я пришел к мысли, что спрятать это будет опрятнее.

2020-10-31 21:51 UTC, serykhelena commented on controller_bb_8_driver/include/logger.h
> +             float value1,
Ок. Делай, как тебе нравится и как считаешь правильным

2020-10-31 21:52 UTC, serykhelena approved these changes

2020-11-13 14:38 UTC, serykhelena commented on controller_bb_8_driver/src/gyroscope.c
> +    chThdSleepMilliseconds(100);
@Doraepod может значение задержки не хардкодить, а засунуть в аргументы инита? Ну, или в дефайн засунуть (тоже хардкод, но если что проще вспомнить об этой задержке)

2020-11-13 22:59 UTC, Doraepod commented on controller_bb_8_driver/src/gyroscope.c
> +    chThdSleepMilliseconds(100);
Сделал

2020-11-14 15:00 UTC, serykhelena approved these changes

2020-11-14 15:04 UTC, merged